services:
  postgres:
    image: postgres:16-alpine
    container_name: pic-scale-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: pic_scale
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    container_name: pic-scale-pgweb
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres123@postgres:5432/pic_scale?sslmode=disable
    ports:
      - '8081:8081'
    depends_on:
      - postgres
  redis:
    image: redis:7-alpine
    container_name: pic-scale-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
  bullboard:
    image: deadly0/bull-board
    container_name: pic-scale-bullboard
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3001:3000'
    depends_on:
      - redis
  minio:
    image: minio/minio:latest
    container_name: pic-scale-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
  upscaler:
    build:
      context: ./services/upscaler
      dockerfile: Dockerfile
    container_name: pic-scale-upscaler
    restart: unless-stopped
    ports:
      - '8000:8000'

volumes:
  postgres_data:
  minio_data: