export const env = {
  NODE_ENV: 'NODE_ENV',
  APP_PORT: 'APP_PORT',

  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',

  MINIO_ENDPOINT: 'MINIO_ENDPOINT',
  MINIO_PORT: 'MINIO_PORT',
  MINIO_USE_SSL: 'MINIO_USE_SSL',
  MINIO_ACCESS_KEY: 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY: 'MINIO_SECRET_KEY',
  MINIO_BUCKET: 'MINIO_BUCKET',

  UPSCALE_FACTOR: 'UPSCALE_FACTOR',
  REALESRGAN_EXECUTABLE: 'REALESRGAN_EXECUTABLE',
} as const;
